<?php
/**
 *
 * This file was auto-generated by OrionFramework
 * www.orionframework.com
 */
 class User extends Doctrine_Record
 {
 	public function setTableDefinition()
 	{
 		$this->hasColumn('id', 'integer', 8, array(
 				'primary'		=> true,
 				'autoincrement'	=> true,
 				'notnull'		=> true
 				)
 		);
 
 	}
 
 	public function setUp()
 	{
 		$this->actAs('UserTemplate');
 
 		$this->actAs('OrionTemplate');
 	}
 }
 