<?php
/**
 *
 * This file was auto-generated by Orion-Framework
 * 
 * www.orion-framework.org
 *
 */
 
 class testIndexCommand extends PHPUnit_Framework_TestCase
 {
 	protected $test 	= 0;
 
 	public function setUp()
 	{
 		$this->test	= new IndexCommand();
 	}
 
 	public function test_IF_Class_IndexCommand_Exists()
 	{
 		$this->assertTrue( class_exists( 'IndexCommand' ) );
 	}
 
 	public function test_IF_Method_execute_Exists()
 	{
 		$this->assertTrue( method_exists( $this->test, 'execute' ) );
 	}
 
 	public function test_IF_Method_getAction_Exists()
 	{
 		$this->assertTrue( method_exists( $this->test, 'getAction' ) );
 	}
 
 }
 