<?php
/**
 *
 * This file was auto-generated by Orion Framework
 *
 * www.orion-framework.org
 */
 class ManagerCommand extends OrionCommand
 {
 	/**
 	 * This is a method of the interface
 	 * ICommand.
  	 */
 	public function execute()
 	{
 		return $this;
 	}
 
 	/**
 	 * This is a method of the interface
 	 * ICommand.
  	 */
 	public function getAction()
 	{
 		return $this;
 	}
 
 }
 