#!/usr/bin/env php
<?php
require(dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "Orion.php");

$argc = $_SERVER['argc'];
$argv = $_SERVER['argv'];
try 
{
	$cli = 	Orion::getInstance()
			->runOrionBuilder_Cli( $argc, $argv );
} catch( Exception $e )
{
	printf("Erro fatal:\n");
	print $e->getMessage() . "\n";
	print $e->getPortableMessage() . "\n";
}
 

