Admin:
  tableName: admin
  columns:
    id:
      type: integer(8)
      autoincrement: true
      notnull: true
      primary: true
    username:
      unique: true
      notnull: true
      type: string(200)
    password:
      notnull: true
      type: string(32)
    firstname:
      notnull: true
      type: string(200)
    email:
      notnull: true
      type: string(200)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    lastname: string(200)
    street: string(255)
    district: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    state_id: integer(8)
    state_foreign: string(255)
    country_id: integer(8)
    cep: string(9)
    tel_res: string(32)
    tel_cel: string(32)
    imagem: string(200)
    last_login: timestamp(25)
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
    Groups:
      class: Group
      local: id
      foreign: admin_id
      type: many
    Roles:
      class: Role
      local: id
      foreign: admin_id
      type: many
City:
  tableName: city
  columns:
    id:
      notnull: true
      primary: true
      autoincrement: true
      type: integer(8)
    state_id: integer(8)
    name: string(255)
    country_id: integer(8)
  relations:
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
    Users:
      class: User
      local: id
      foreign: city_id
      type: many
    Admins:
      class: Admin
      local: id
      foreign: city_id
      type: many
    ConfigSchools:
      class: ConfigSchool
      local: id
      foreign: city_id
      type: many
    Companies:
      class: Company
      local: id
      foreign: city_id
      type: many
    Responsibles:
      class: Responsible
      local: id
      foreign: city_id
      type: many
    Students:
      class: Student
      local: id
      foreign: city_id
      type: many
    Teachers:
      class: Teacher
      local: id
      foreign: city_id
      type: many
Course:
  tableName: course
  columns:
    id:
      notnull: true
      autoincrement: true
      primary: true
      type: integer(8)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    name: string(200)
    description: string(5000)
    language_id: integer(8)
    created_by: string(200)
  relations:
    CourseStudent:
      local: id
      foreign: course_id
      type: many
    Language:
      local: language_id
      foreign: id
      type: one
Company:
  tableName: company
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    name:
      notnull: true
      type: string(255)
    cnpj:
      notnull: true
      type: string(255)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    tel: string(200)
    tel_fax: string(200)
    email_contact: string(255)
    email_finance: string(255)
    address: string(255)
    number: string(8)
    complement: string(255)
    district: string(255)
    country_id: integer(8)
    state_id: integer(8)
    state_foreign: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    cep: string(10)
  relations:
    Country:
      local: country_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    City:
      local: city_id
      foreign: id
      type: one
    Students:
      class: Student
      local: id
      foreign: company_id
      type: many
Notify:
  tableName: notify
  columns:
    id:
      primary: true
      notnull: true
      autoincrement: true
      type: integer(8)
    subject: string(500)
    message: string(2000)
    headers: string(2000)
ConfigPortal:
  tableName: config_portal
  columns:
    id:
      autoincrement: true
      notnull: true
      primary: true
      type: integer(4)
    domain:
      notnull: true
      type: string(255)
    default_title: string(255)
    meta_description: string(500)
    meta_keywords: string(500)
    approve_profile: integer(1)
    auth_email: integer(1)
    smtp_email: string(255)
    port_email: integer(8)
    user_email: string(255)
    pass_email: string(255)
    allow_ssl: integer(1)
    allow_logs: integer(1)
    login_admin: string(200)
ConfigSchool:
  tableName: config_school
  columns:
    id:
      notnull: true
      autoincrement: true
      primary: true
      type: integer(4)
    company_name: string(255)
    commercial_name: string(255)
    cnpj: string(18)
    street: string(255)
    district: string(255)
    city_id: integer(8)
    state_id: integer(8)
    country_id: integer(8)
    zip: string(20)
    telefone: string(255)
    telefone_fax: string(255)
    email_main: string(255)
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
Country:
  tableName: country
  columns:
    iso:
      unique: true
      type: string(2)
    iso3:
      unique: true
      type: string(3)
    id:
      primary: true
      notnull: true
      autoincrement: false
      type: integer(8)
    name: string(255)
  relations:
    State:
      local: id
      foreign: country_id
      type: many
    Cities:
      class: City
      local: id
      foreign: country_id
      type: many
    Users:
      class: User
      local: id
      foreign: country_id
      type: many
    Students:
      class: Student
      local: id
      foreign: country_id
      type: many
    Teachers:
      class: Teacher
      local: id
      foreign: country_id
      type: many
    Admins:
      class: Admin
      local: id
      foreign: country_id
      type: many
    ConfigSchools:
      class: ConfigSchool
      local: id
      foreign: country_id
      type: many
    Companies:
      class: Company
      local: id
      foreign: country_id
      type: many
    Responsibles:
      class: Responsible
      local: id
      foreign: country_id
      type: many
Teacher:
  tableName: teacher
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    firstname: string(255)
    lastname: string(255)
    acronym: string(2)
    cpf: string(14)
    rg: string(14)
    tel_res: string(30)
    tel_cel: string(30)
    email: string(255)
    address: string(255)
    number: string(8)
    complement: string(255)
    district: string(255)
    state_id: integer(8)
    state_foreign: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    country_id: integer(8)
    bank_name: string(200)
    ag_bank: string(200)
    account_bank: string(200)
    day_disp: string(500)
    date_admission: timestamp(25)
    readjustment: timestamp(25)
  relations:
    Country:
      local: country_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    City:
      local: city_id
      foreign: id
      type: one
    TeacherLanguage:
      local: id
      foreign: teacher_id
      type: many
Flag:
  tableName: flag
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    name:
      unique: true
      type: string(255)
    resource_id: integer(8)
  relations:
    Users:
      class: User
      local: id
      foreign: flag_id
      type: many
    Resources:
      class: Resource
      local: resource_id
      foreign: id
      type: one
Group:
  tableName: groups
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    name:
      unique: true
      type: string(255)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    description: string(500)
    admin_id: integer(8)
    role_id: integer(8)
  relations:
    Users:
      class: User
      local: id
      foreign: group_id
      type: many
    Role:
      local: role_id
      foreign: id
      type: one
    Admin:
      local: admin_id
      foreign: id
      type: one
PedagogicStudent:
  tableName: pedagogic_student
  columns:
    id:
      notnull: true
      primary: true
      autoincrement: true
      type: integer(8)
    nr_children: integer(4)
    hobby: string(255)
    expectations: string(500)
  relations:
    Student:
      local: id
      foreign: pedagogic_id
      type: many
CivilStatus:
  tableName: civil_status
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    name: string(200)
  relations:
    Student:
      local: id
      foreign: civilstatus_id
      type: many
    Responsible:
      local: id
      foreign: civilstatus_id
      type: many
Resource:
  tableName: resource
  columns:
    id:
      primary: true
      notnull: true
      autoincrement: true
      type: integer(8)
    name: string(200)
    service_id: integer(8)
  relations:
    Service:
      local: service_id
      foreign: id
      type: one
    Roles:
      refClass: RoleResource
      class: Role
      local: resource_id
      foreign: role_id
      type: many
    Flags:
      class: Flag
      local: id
      foreign: resource_id
      type: many
    RoleResource:
      local: id
      foreign: resource_id
      type: many
RespRel:
  tableName: resp_rel
  columns:
    id:
      autoincrement: true
      notnull: true
      primary: true
      type: integer(8)
    resp_id:
      notnull: true
      autoincrement: false
      type: integer(8)
    type_resp:
      notnull: true
      type: integer(1)
  relations:
    Student:
      local: id
      foreign: foreign
      type: one
Language:
  tableName: language
  columns:
    id:
      notnull: true
      autoincrement: true
      primary: true
      type: integer(8)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    name: string(200)
    created_by: string(200)
  relations:
    Course:
      local: id
      foreign: language_id
      type: many
    TeacherLanguage:
      local: id
      foreign: language_id
      type: many
Responsible:
  tableName: responsible
  columns:
    id:
      primary: true
      notnull: true
      autoincrement: true
      type: integer(8)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    firstname: string(255)
    lastname: string(255)
    cpf: string(14)
    rg: string(14)
    civilstatus_id: integer(8)
    nationality: string(255)
    tel_res: string(30)
    tel_cel: string(30)
    email_part: string(255)
    email_pro: string(255)
    address: string(255)
    number: string(8)
    complement: string(255)
    district: string(255)
    state_id: integer(8)
    state_foreign: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    country_id: integer(8)
    cep: string(10)
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
    CivilStatus:
      local: civilstatus_id
      foreign: id
      type: one
GradeSchool:
  tableName: grade_school
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    name: string(200)
  relations:
    Student:
      local: id
      foreign: gradeschool_id
      type: many
Role:
  tableName: role
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    name: string(200)
    admin_id: integer(8)
    description: string(5000)
  relations:
    Admin:
      local: admin_id
      foreign: id
      type: one
    Resources:
      refClass: RoleResource
      class: Resource
      local: role_id
      foreign: resource_id
      type: many
    RoleResource:
      local: id
      foreign: role_id
      type: many
RoleResource:
  tableName: role_resource
  columns:
    role_id:
      primary: true
      type: integer(8)
    resource_id:
      primary: true
      type: integer(8)
    op_create: integer(1)
    op_update: integer(1)
    op_delete: integer(1)
    op_see: integer(1)
  relations:
    Resource:
      local: resource_id
      foreign: id
      type: one
    Role:
      local: role_id
      foreign: id
      type: one
Service:
  tableName: service
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    name: string(255)
  relations:
    Resources:
      class: Resource
      local: id
      foreign: service_id
      type: many
State:
  tableName: state
  columns:
    id:
      notnull: true
      autoincrement: true
      primary: true
      type: integer(8)
    uf:
      unique: true
      type: string(2)
    name: string(255)
    country_id: integer(8)
  relations:
    Country:
      local: country_id
      foreign: id
      type: one
    Cities:
      class: City
      local: id
      foreign: state_id
      type: many
    Users:
      class: User
      local: id
      foreign: state_id
      type: many
    Admins:
      class: Admin
      local: id
      foreign: state_id
      type: many
    ConfigSchools:
      class: ConfigSchool
      local: id
      foreign: country_id
      type: many
    Companies:
      class: Company
      local: id
      foreign: state_id
      type: many
    Responsibles:
      class: Responsible
      local: id
      foreign: state_id
      type: many
    Students:
      class: Student
      local: id
      foreign: state_id
      type: many
    Teachers:
      class: Teacher
      local: id
      foreign: state_id
      type: many
Student:
  tableName: student
  columns:
    id:
      primary: true
      notnull: true
      autoincrement: true
      type: integer(8)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    firstname: string(255)
    lastname: string(255)
    cpf: string(14)
    rg: string(15)
    gradeschool_id: integer(8)
    civilstatus_id: integer(8)
    email_part: string(255)
    birthday: date(25)
    tel_res: string(100)
    tel_cel: string(100)
    nationality: string(100)
    i_resp: integer(1)
    responsible_id: integer(8)
    pedagogic_id: integer(8)
    company_id: integer(8)
    addr_corresp: integer(1)
    country_id: integer(8)
    address: string(255)
    number: string(8)
    complement: string(255)
    district: string(255)
    state_id: integer(8)
    state_foreign: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    cep: string(10)
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
    PedagogicStudent:
      local: pedagogic_id
      foreign: id
      type: one
    RespRel:
      local: responsible_id
      foreign: id
      type: one
    Company:
      local: company_id
      foreign: id
      type: one
    CivilStatus:
      local: civilstatus_id
      foreign: id
      type: one
    GradeSchool:
      local: gradeschool_id
      foreign: id
      type: one
    CourseStudent:
      local: id
      foreign: student_id
      type: many
User:
  tableName: user
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    username:
      unique: true
      notnull: true
      type: string(200)
    firstname:
      notnull: true
      type: string(255)
    email:
      notnull: true
      type: string(255)
    group_id:
      notnull: true
      type: integer(8)
    created_at:
      notnull: true
      type: timestamp(25)
    updated_at:
      notnull: true
      type: timestamp(25)
    password: string(32)
    lastname: string(255)
    street: string(255)
    district: string(255)
    city_id: integer(8)
    city_foreign: string(255)
    state_id: integer(8)
    state_foreign: string(255)
    country_id: integer(8)
    cep: string(9)
    tel_res: string(32)
    tel_cel: string(32)
    imagem: string(200)
    last_login: timestamp(25)
    last_iteration: timestamp(25)
    flag_id: integer(8)
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Country:
      local: country_id
      foreign: id
      type: one
    Group:
      local: group_id
      foreign: id
      type: one
    Flag:
      local: flag_id
      foreign: id
      type: one
CourseStudent:
  tableName: course_student
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    nr_contract: string(100)
    date_contract: date(25)
    student_id: integer(8)
    course_id: integer(8)
    course_book: string(255)
    appraised_for: string(255)
    level: integer(4)
    pays_material: 'decimal(18, 2)'
    date_pay_material: date(25)
    value_pay_per: 'decimal(18, 2)'
    pay_per: integer(1)
    value_total_per_month: 'decimal(18, 2)'
    value_registration: 'decimal(18, 2)'
    date_pay_first_monthly: date(25)
    amount_hours_month: integer(8)
    date_expire: date(25)
    observations: string(2000)
  relations:
    Student:
      local: student_id
      foreign: id
      type: one
    Course:
      local: course_id
      foreign: id
      type: one
TeacherLanguage:
  tableName: teacher_language
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    teacher_id: integer(8)
    language_id: integer(8)
    pronunciation: string(255)
    ntredacao: string(8)
    ntteste: string(8)
  relations:
    Teacher:
      local: teacher_id
      foreign: id
      type: one
    Language:
      local: language_id
      foreign: id
      type: one
CompanyStudent:
  tableName: company_student
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(8)
    student_id:
      notnull: true
      type: integer(8)
    company_id:
      notnull: true
      type: integer(8)
    company_position: string(255)
    student_email_company: string(255)
